[package]
name = "blog_os"
version = "0.1.0"
edition = "2018"

[profile.dev]
panic = "abort" #禁止panic时展开调用栈
[profile.release]
panic = "abort"

[dependencies]
#将可执行程序转换为可引导的映像需要将其与引导程序进行链接，引导程序负责初始化CPU并加载内核
bootloader = "0.9" # 直接使用现有的BIOS引导程序
volatile = "0.2.6" # 避免读写操作被rust编译器优化