#处理不同平台的构建参数
[target.'cfg(target_os = "linux")']
rustflags = ["-C", "link-arg=-nostartfiles"]

[target.'cfg(target_os = "windows")']
rustflags = ["-C", "link-args=/ENTRY:_start /SUBSYSTEM:console"]

[target.'cfg(target_os = "macos")']
rustflags = ["-C", "link-args=-e __start -static -nostartfiles"]
#unstable新特性
[unstable]
#重新编译核心和其他标准库crate，而不是使用Rust安装附带的预编译版本
#build-std = ["core", "compiler_builtins"]当core启用时，compiler_builtins默认处于启用状态
build-std = ["core"]
build-std-features = ["compiler-builtins-mem"]
#配置build时默认的--target参数
[build]
target = "x86_64-blog_os.json"
#指定编译完成后运行可执行文件的运行器，需要在浏览器中下载
[target.x86_64-blog_os]
#runner = "qemu-system-x86_64"
#筛选出三元组中宿主设置了none的所有编译目标
[target.'cfg(target_os = "none")']
#使用cargo run即可编译内核并在QEMU中启动
runner = "bootimage runner"